# TOML config
#log_path = "./main-server.log" #uncomment if want log to file

[server]
ip              = "localhost"
grpc_port       = 8000
http_port       = 8001
ticker_time_min = 5

[db]
industries_source = "./db/stocks.json"


